config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post
  after_save :update_comments_counter
  after_destroy :decrease_comments_counter

  validates :text, presence: true, length: { in: 2..100 }

  # A method that updates the comments counter for a post.
  def update_comments_counter
    post.increment!(:comments_counter)
  end

  def decrease_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post
  after_save :update_likes_counter
  after_destroy :decrease_likes_counter

  # A method that updates the likes counter for a post.
  def update_likes_counter
    post.increment!(:likes_counter)
  end

  def decrease_likes_counter
    post.decrement!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy, foreign_key: :post_id
  has_many :likes, dependent: :destroy, foreign_key: :post_id
  after_save :update_posts_counter
  after_destroy :decrease_posts_counter

  attribute :comments_counter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0

  validates :title, presence: true, length: { in: 2..250 }
  validates :text, presence: true, length: { in: 10..600 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # A method which returns the 5 most recent comments for a given post.
  def recent_comments
    comments.includes(:author).order(created_at: :asc).limit(5)
  end

  # A method that updates the posts counter for a user.
  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def decrease_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy, foreign_key: :author_id
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  attribute :posts_counter, :integer, default: 0

  validates :name, presence: true, length: { minimum: 2 }
  validates :photo, presence: true
  validates :bio, presence: true, length: { in: 10..250 }
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.includes(:author).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])

    if @comment.save
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    @like.save!
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes([:posts]).find(params[:user_id])
    @posts = @user.posts.includes([:comments]).order(created_at: :asc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div>
  <h2>Add a comment:</h2>
  <%= form_with model: @comment, url: user_post_comments_path  do |form| %>
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= render partial: "shared/userslinks" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post, url: user_posts_path do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text %><br>
    <% post.errors.full_messages_for(:text).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like.html.erb
<%= form_with model: @like, url: user_post_likes_path(user_id: @post.author.id, post_id: @post), local: true do |form| %>
  <%= form.submit "Like ❤️" %>
<% end %>

app/views/posts/index.html.erb
<section class="user-section">
  <div class="user-profile">
    <% if @user.photo.present? %>
      <%= image_tag(@user.photo, class: 'img', alt: 'User photo', width: 200, height: 150) %>
    <% else %>
      <%= image_tag('photo.jpg', alt: 'User photo', width: 200, height: 150) %>
    <% end %>
    <div class="user-details">
      <h2 class="username">Username: <%= @user.name %></h2>
      <p class="post-counter">Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class="post">
    <% @posts.each do |post| %>
      <%= link_to "/users/#{@user.id}/posts/#{post.id}", class: 'user-posts' do %>
        <div class='user-wraps'>
          <h3 class="secundary-text">Post #<%= post.id %> <%= post.title %></h3>
          <p class="text"><%= post.text %></p>
          <span class="post-counter text">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
        </div>
        <% if post.recent_comments.empty? %>
          <div class="post-comments"> 
            <p class="text pink">Comments:</p>
            <p class="text">There are no comments</p>
          </div>
        <% else %>
          <div class="post-comments"> 
            <p class="text pink">Comments:</p>
            <% post.recent_comments.each do |comment| %>
              <p class="text"><%= comment.author.name %>: <span class="brown"> <%= comment.text %> </span> </p>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <a class="btn secundary-text" href="#">Pagination</a>
</section>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render partial: "form", locals: { post: @post } %>

app/views/posts/show.html.erb
<section class="user-section">
  <div class="post">
    <div class='user-wraps'>
      <div class="flex">
        <h3 class="secundary-text">Post #<%= @post.id %> <%= @post.title %></h3>
        <span class="text">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></span>
      </div>
      <p class="text"><%= @post.text %></p>
      <div class="new-like">
        <%= render partial: "like", locals: { like: Like.new, post_id: @post.id, user_id: @post.author.id } %>
      </div>
    </div>
    <div class="post-comments"> 
      <p class="text pink">Comments:</p>
      <% if @post.comments.empty? %>
        <p class="text">There are no comments</p>
      <% else %>
        <% @post.comments.each do |comment| %>
          <p class="text">
            <%= comment.author.name %>: <span class="brown"> <%= comment.text %> </span>
          </p>
        <% end %>
      <% end %>
    </div>
    <%= link_to "Add a comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id), class: "btn secundary-text" %>
  </div>
</section>

app/views/shared/_userslinks.html.erb
<div>
  <% if user_signed_in?  %>
    <%= link_to "Edit profile", edit_user_registration_path, class: 'btn secundary-text' %>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn secundary-text'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, class: 'btn secundary-text'  %>
    <%= link_to "Login", new_user_session_path, class: 'btn secundary-text' %>
  <% end %>
</div>

app/views/users/index.html.erb
<section class="users-section">
  <ul class="user-list">
    <% @users.order(id: :asc).each do |user| %>
      <li>
        <%= link_to user, class: 'user-link' do %>
          <div class="user-profile">
            <% if user.photo.present? %>
              <%= image_tag(user.photo, class: 'img', alt: 'User photo', width: 200, height: 150) %>
            <% else %>
              <%= image_tag('photo.jpg', alt: 'User photo', width: 200, height: 150) %>
            <% end %>
            <div class="user-details">
              <h2 class="username">Username: <%= user.name %></h2>
              <p class="post-counter">Number of posts: <%= user.posts_counter %></p>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section class="user-section">
  <div class="user-profile">
    <% if @user.photo.present? %>
      <%= image_tag(@user.photo, class: 'img', alt: 'User photo', width: 200, height: 150) %>
    <% else %>
      <%= image_tag('photo.jpg', alt: 'User photo', width: 200, height: 150) %>
    <% end %>
    <div class="user-details">
      <h2 class="username">Username: <%= @user.name %></h2>
      <p class="post-counter">Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class="user-wraps">
    <h3 class="secundary-text">Bio</h3>
    <p class="text"><%= @user.bio %></p>
  </div>
  <% unless @user.recent_posts.empty? %>
    <div class="user-posts">
      <% @user.recent_posts.each do |post| %>
        <%= link_to "/users/#{@user.id}/posts/#{post.id}", class: 'user-wraps' do %>
          <h3 class="secundary-text">Post #<%= post.id %> <%= post.title %></h3>
          <p class="text"><%= post.text %></p>
          <span class="post-counter text">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
        <% end %>
      <% end %>
    </div>
  <% else %>
  <% end %>
  <% if @user.recent_posts.present? %>
    <%= link_to "See all posts", user_posts_path(@user),  class: "btn secundary-text" %>
    <%= link_to "New post", new_user_post_path(@user), class: "btn secundary-text" %>
  <% end %>
</section>